# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88aac13ffa0c4bdf6765048d0e70b699d224a2361da4abac97b7c96d611d008d8fe710fe8463b3b023518f872b02834bcdbdc1d138684bf7798bf4a4716bab63

test:
  secret_key_base: 97af765d7e5b9658c8c1a43f284f781bdf68aacecd000146a38d5643d13173e0c96eb20cac0fe56545bddfd7d1642efa3e69c7c6fee7ef1597b5c44fd2bd4a35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
